#!/bin/bash
#
# Generate segment files as follows:
# o Fixed size data records
# o Data record length, in bytes: 1
# o Data section size, in bytes: 1
#
# Number of records: 5
#
# Expect raw number of segment files: 5
# Delete segment files: 1, 3, and 4

set -eu

PFX=pfx-
SFX=.log

bin="$(dirname "$0")/../bin"

FORMAT="fixed:1"
DELETE="1 3 4"
DATA_SIZE="1"
NUMBER="5"

$bin/error-recovery-common \
    -e "recovery-fixed_1-1.expected" \
    -f "$FORMAT" \
    -d "$DELETE" \
    -s "$DATA_SIZE" \
    -n "$NUMBER" \
    "$@"
