#!/bin/bash
#
# Generate segment files as follows:
# o Fixed size data records
# o Data record Length, in bytes: 5
# o Data section size, in bytes: 17
#
# Number of records: 20
#
# Expect raw number of segment files: 5
# Delete segment files 1, 3, and 4

set -eu

PFX=pfx-
SFX=.log

test="$(dirname "$0")"

FORMAT="fixed:5"
DELETE="1 3 4"
DATA_SIZE="17"
NUMBER=20

$test/error-recovery-common \
    -e "recovery-fixed_5-17.expected" \
    -f "$FORMAT" \
    -d "$DELETE" \
    -s "$DATA_SIZE" \
    -n "$NUMBER" \
    "$@"
