#!/bin/bash
#
# This runs tcslog-gen to generate segment files. It then deletes and
# corrupts them in various ways and uses tcslog-dump to see whether
# error recovery works.
# working correctly. It's also helpful in checking out tcslog-dump.

set -eu

TMP_DIR=/tmp/t1
PFX=pfx-
SFX=.log

test="$(dirname "$0")"

FORMAT="variable-simple:0..10"
DELETE="1 3 4"
DATA_SIZE="17"
NUMBER=20

$test/error-recovery-common \
    -e "variable_0-10-17.expected" \
    -f "$FORMAT" \
    -d "$DELETE" \
    -s "$DATA_SIZE" \
    -n "$NUMBER" \
    "$@"
