#!/bin/bash
#
# This runs tcslog-gen to generate segment files. It then deletes and
# corrupts them in various ways and uses tcslog-dump to see whether
# error recovery works.
# working correctly. It's also helpful in checking out tcslog-dump.

set -eu

PFX=pfx-
SFX=.log

bin="$(dirname "$0")/../bin"

FORMAT="variable-tsrc:0..10"
DELETE="1 3 4"
DATA_SIZE="21"
NUMBER=20

$bin/error-recovery-common \
    -e "variable-tsrc_0-10-21.expected" \
    -f "$FORMAT" \
    -d "$DELETE" \
    -s "$DATA_SIZE" \
    -n "$NUMBER" \
    "$@"
