[package]
name = "tcslog-dump"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tcslog = { path = "../tcslog", default-features = false }
clap.workspace = true

[lints]
workspace = true
